apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-05-28T01:26:16Z"
  labels:
    run: mosquito
  name: mosquito
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: mosquito
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
