apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: efk
spec:
  storageClassName: elasticsearch-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
 #persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/elasticsearch-volume/
