apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: efk
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
 #persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongodb-volume/
