apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myubuntu
  name: myubuntu
spec:
  containers:
  - image: docker-registry.sadaiyer.com:5000/myubuntu-nginx:v1
    name: myubuntu
    imagePullPolicy: Always
    resources: {}
  imagePullSecrets:
  - name: dockercredentials
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
